services:
  ping360_sonar:
    build: .
    container_name: ping360_sonar
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
      - ROS_DISTRO=humble
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
