services:
  barracuda-ping-360:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: barracuda-ping-360
    container_name: barracuda-ping-360
    user: root
    privileged: true
    tty: true
    network_mode: host
    ipc: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ${HOME}/.ssh:/root/.ssh
  barracuda-ping-360-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    image: barracuda-ping-360-dev
    container_name: barracuda-ping-360-dev
    tty: true
    network_mode: host
    ipc: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.vimrc:/root/.vimrc
      - ../barracuda_control:/ros2_ws/src/barracuda_control
    profiles: ["dev"]
